# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-20 23:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import repositorio.lib.Archivos


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(help_text='Nombres del Autor del Objeto.', max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(help_text='Apellidos del Autor del Objeto.', max_length=100, verbose_name='Apellidos')),
                ('rol', models.CharField(default='Autor', help_text='Papel que juega en la creación del Objeto', max_length=100, verbose_name='Rol')),
            ],
            options={
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='EspecificacionLOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lc1_titulo', models.CharField(help_text='Nombre para el objeto', max_length=200, unique=True, verbose_name='Título')),
                ('lc1_idioma', models.CharField(choices=[('sp', 'Español'), ('en', 'Inglés'), ('fr', 'Francés'), ('it', 'Italiano'), ('ja', 'Japonés'), ('pt', 'Portugués'), ('ru', 'Ruso'), ('sv', 'Suizo'), ('de', 'Alemán'), ('zh', 'Chino')], default='sp', help_text='Lenguaje predominante en el objeto', max_length=2, verbose_name='Idioma')),
                ('lc1_descripcion', models.TextField(help_text='Descripción Textual del contenido del objeto', verbose_name='Descripción')),
                ('lc1_cobertura', models.TextField(blank=True, help_text='Lugar, tiempo, cultura, geografía o región en la cual el objeto es aplicado', null=True, verbose_name='Cobertura')),
                ('lc1_nivel_agregacion', models.CharField(choices=[('N1', 'Recursos Digitales'), ('N2', 'Colección de Recursos'), ('N3', 'Colección de Lecciones'), ('N4', 'Colección de Cursos')], default='N1', help_text='Granularidad Funcional del objeto.', max_length=2, verbose_name='Nivel de Agregación')),
                ('lc2_version', models.CharField(default='1.0', help_text='La edición del objeto', max_length=50, verbose_name='Versión')),
                ('lc2_fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha en que el objeto es publicado', verbose_name='Fecha de Publicación')),
                ('lc3_requerimientos', models.TextField(blank=True, help_text='Capacidades técnicas requeridas para usar este objeto', null=True, verbose_name='Requerimientos')),
                ('lc3_instrucciones', models.TextField(blank=True, help_text='Descripción de cómo usar este objeto.', null=True, verbose_name='Instrucciones')),
                ('lc4_tipo_inter', models.CharField(choices=[('act', 'Activo'), ('exp', 'Expositivo')], default='exp', help_text='Modo predominante del aprendizaje que aplica este objeto', max_length=3, verbose_name='Tipo de Interactividad')),
                ('lc4_tipo_rec', models.CharField(choices=[('plain/text', 'Lectura'), ('application/xhtml', 'Página Web'), ('application/pdf', 'Lectura/PDF'), ('application/zip', 'Empaquetado'), ('image/jpeg', 'Imagen/Gráfico/Illustración'), ('audio/mpeg', 'Audio'), ('video/mpeg', 'Video/mpg'), ('video/mp4', 'Video/mp4'), ('video/x-ms-wmv', 'Video/wmv'), ('video/quicktime', 'Video/mov'), ('video/x-flv', 'Video/flv'), ('application/x-shockwave-flash', 'Animación')], default='plain/text', help_text='Tipo de recurso de aprendizaje.', max_length=50, verbose_name='Tipo de Recurso de Aprendizaje')),
                ('lc4_nivel_inter', models.CharField(choices=[('mba', 'Muy Bajo'), ('baj', 'Bajo'), ('med', 'Medio'), ('alt', 'Alto'), ('mal', 'Muy Alto')], default='mba', help_text='Grado de interactividad que predomina en el objeto.', max_length=3, verbose_name='Nivel de Interactividad')),
                ('lc4_poblacion', models.TextField(blank=True, help_text='Descripción de los Usuarios para los cuales este objeto fue diseñado.', null=True, verbose_name='Población')),
                ('lc4_contexto', models.CharField(choices=[('EPre', 'Educación Preescolar'), ('EBas', 'Educación Básica'), ('EMed', 'Educación Media'), ('ESup', 'Educación Superior'), ('ETra', 'Educación para el Trabajo')], default='EPre', help_text='Principal ambiente en el cual este objeto es utilizado.', max_length=4, verbose_name='Contexto')),
                ('lc5_derechos', models.TextField(help_text='Condiciones de uso de este objeto. Ejp: copyright, Creative Commons', verbose_name='Derechos de Uso')),
                ('lc6_uso_educativo', models.TextField(blank=True, help_text='Anotación sobre el uso educativo del objeto', null=True, verbose_name='Uso Educativo')),
            ],
            options={
                'verbose_name': 'Metadato',
                'verbose_name_plural': 'Metadatos',
            },
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicado', models.BooleanField(default=False, help_text='Marca para publicar en repositorio', verbose_name='Publicado')),
                ('tipo_obj', models.CharField(choices=[('ova', 'Objeto Virtual de Aprendizaje'), ('rda', 'Recurso Digital')], default='rda', help_text='Tipo de Objeto', max_length=3, verbose_name='Tipo de Objeto')),
                ('archivo', models.FileField(help_text='Archivo a Subir', upload_to=repositorio.lib.Archivos.get_file_path, verbose_name='Archivo')),
                ('autores', models.ManyToManyField(help_text='Personas autoras del objeto', to='gestorObjetos.Autor')),
                ('creador', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('espec_lom', models.OneToOneField(help_text='Metadatos para el objeto', on_delete=django.db.models.deletion.CASCADE, to='gestorObjetos.EspecificacionLOM', verbose_name='Metadato')),
            ],
        ),
        migrations.CreateModel(
            name='PalabraClave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra_clave', models.CharField(help_text='Palabra que describe el Objeto', max_length=50, unique=True, verbose_name='Palabra Clave')),
            ],
            options={
                'verbose_name': 'Palabra Clave',
                'verbose_name_plural': 'Palabras Clave',
            },
        ),
        migrations.CreateModel(
            name='Repositorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre que identifica al repositorio', max_length=200, unique=True, verbose_name='Nombre del Repositorio')),
                ('publico', models.BooleanField(default=True, help_text='Marca para habilitar el repositorio al público', verbose_name='Público')),
                ('grupos', models.ManyToManyField(blank=True, null=True, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='RutaCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ruta', models.CharField(help_text='Nombre de la Categoría.', max_length=150, verbose_name='Categoría')),
                ('cat_padre', models.ForeignKey(blank=True, help_text='Categoría que la contiene', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='gestorObjetos.RutaCategoria', verbose_name='Categoría Padre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('rest', 'Estudiante'), ('rdoc', 'Docente'), ('radm', 'Administrador'), ('rcat', 'Catalogador'), ('rrev', 'Revisor')], default='rest', help_text='Rol que identifica la participación del :model:"User" en el sistema', max_length=4, verbose_name='Rol de Usuario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.AddField(
            model_name='objeto',
            name='palabras_claves',
            field=models.ManyToManyField(help_text='Palabras asociadas al objeto.', to='gestorObjetos.PalabraClave'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='repositorio',
            field=models.ForeignKey(help_text='Repositorio donde se aloja el objeto', on_delete=django.db.models.deletion.CASCADE, to='gestorObjetos.Repositorio'),
        ),
        migrations.AddField(
            model_name='objeto',
            name='ruta_categoria',
            field=models.ForeignKey(help_text='Categoría o área de conocimiento', on_delete=django.db.models.deletion.CASCADE, to='gestorObjetos.RutaCategoria'),
        ),
    ]
